### ISSUE TITLE
Not downloadable/not working

### ISSUE THREAD

**Issue by EliseAld** [oganm/geneSynonym#8]
Hello,
I tried to install the package with
install_github('oganm/geneSynonym')
on a windows machine but it times out every time. On a Mac machine, I could install it but when I try to run it (eg humanSyno('Mog') ) I get the following error message
Error in humanSyno("Mog") : could not find function "humanSyno"
Could you please help me out ?
Thanks !

**Comment by oganm** [comment]
Are you sure the install ended succesfully on Mac and did you do `library(geneSynonym)` first? If the installation was really successful and the function isn't there after loading the library not sure what could be happening and need more info. If installation is failing, error message would help

On Windows can you install anything else with `install_github`?

 Just noticed an issue that affect detached behaviour and that is fixed but that doesn't seem to be the problem with you.

**Comment by EliseAld** [comment]
Thanks for the fast reply !
I can’t install anything with install_github on Windows indeed, but now it works on Mac anyway (I forgot to download the library eventually…)
Thank you so much !

---------------------------------
Elise Amblard, PhD student
Soumelis team - Integrative Biology of Human Dendritic Cells and T Cells
Institut Curie, U932
26 rue d'Ulm, 75005 Paris

De : Burak Ogan Mancarci [mailto:notifications@github.com]
Envoyé : lundi 25 juin 2018 22:04
À : oganm/geneSynonym
Cc : Amblard Elise; Author
Objet : Re: [oganm/geneSynonym] Not downloadable/not working (#8)


Are you sure the install ended succesfully on Mac and did you do library(geneSynonym) first? If the installation was really successful and the function isn't there after loading the library not sure what could be happening and need more info. If installation is failing, error message would help

On Windows can you install anything else with install_github?

Just noticed an issue that affect detached behaviour and that is fixed but that doesn't seem to be the problem with you.

**Comment by oganm** [comment]
No problem. For the `install_github` problem you can try to open an issue on the devtools repository
